# Generated by Django 3.2.3 on 2021-05-24 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='writer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgame.user'),
        ),
    ]
