# Generated by Django 3.2.3 on 2021-05-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgame', '0002_alter_community_writer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='writer_id',
            new_name='name',
        ),
    ]
